In [20]:
import numpy as np 

arr = np.array([1,2,3])
print("1:",arr)
print(end = '\n')
arr = np.array([[1, 2, 3],[4, 5, 6],[5,6,7]])
print("2:\n",arr)
print(end = '\n')
arr = np.array((1,3,2))
print("3:",arr)

1: [1 2 3]

2:
 [[1 2 3]
 [4 5 6]
 [5 6 7]]

3: [1 3 2]


In [31]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2:\n",arr)
print(end = '\n')


sliced_arr = arr[:2, :2]
print(sliced_arr)

2:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2]
 [4 5]]


In [47]:
arr = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,8]])

sliced_arr = arr[:2, ::2]
print(sliced_arr)

#                0 1 2
arr = np.array([[1,2,3],  # 0
                [4,5,6],  # 1
                [7,8,9]]) # 2

Index_arr = arr[[1, 1], #row
                [2, 1]] #col 

# (1,2) ,(1,1)
print(Index_arr)

[[1 3]
 [4 6]]
[6 5]


In [33]:
sliced_arr = arr[:2, ::2]
print(sliced_arr)

[[1 3]
 [4 6]]


In [48]:
# add element 

In [53]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a+1)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [68]:
import numpy as np 

a = np.array([[1,3],
              [2,3]])
print("Array:\n",a)
print("After addition:")
print(a+1)

Array:
 [[1 3]
 [2 3]]
After addition:
[[2 4]
 [3 4]]


In [56]:
# subtract elemet 

In [67]:
import numpy as np 

a = np.array([[1,3],
              [2,3]])
print("Array:\n",a)
print("After subtraction:")
print(a-1)

Array:
 [[1 3]
 [2 3]]
After subtraction:
[[0 2]
 [1 2]]


In [61]:
# sum of all array elements 

In [62]:
a.sum()

9

In [ ]:
# Adding 2 arrays

In [66]:
a = np.array([[1,3],
              [2,3]])

b = np.array([[1,3],
              [2,3]])

print("Adding two arrays:")
print(a+b)

Adding two arrays:
[[2 6]
 [4 6]]


In [134]:
# multiplying 2 arrays and 2 matrices 

In [133]:
a = np.array([[1,3],
              [2,3]])

b = np.array([[1,3],
              [2,3]])

print("Multiplying two arrays:")
print(a*b)
print ("Matrix multiplication:\n", a.dot(b))

Multiplying two arrays:
[[1 9]
 [4 9]]
Matrix multiplication:
 [[ 7 12]
 [ 8 15]]


In [80]:
# datatype 

In [69]:
print(a.dtype)

int32


In [75]:
x = np.array([1.0, 2.0]) 
print(x.dtype)

float64


In [79]:
x = np.array([1.0, 2.0], dtype = np.int32)   
print("\nForcing a Datatype: ")
print(x.dtype)
print(x)


Forcing a Datatype: 
int32
[1 2]


In [ ]:
# operations 

In [95]:
a = np.array([[4,9],
              [9,16]])

b = np.array([[1,3],
              [2,3]])

x = np.add(a,b)
print(x)

[[ 5 12]
 [11 19]]


In [96]:
x = np.sqrt(a)
print(x)

[[2. 3.]
 [3. 4.]]


In [97]:
b = b.T
print(b)

[[1 2]
 [3 3]]


In [98]:
# basic array operations 

In [106]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(type(a))
print("Array dimensions:",a.ndim)
print("Shape of array:",a.shape)
print("Size of array:",a.size)
print("Elements datatype:",a.dtype)

<class 'numpy.ndarray'>
Array dimensions: 2
Shape of array: (2, 4)
Size of array: 8
Elements datatype: int32


In [109]:
#creating 2x2 array with zeroes 

x = np.zeros((2,2))
print(x)

[[0. 0.]
 [0. 0.]]


In [110]:
# creating 2x2 array with constant value 6 

x = np.full((2,2),6)
print(x)

[[6 6]
 [6 6]]


In [111]:
# creating 2x2 array with constant value 6 with type : complex

x = np.full((2,2),6,dtype='complex')
print(x)

[[6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j]]


In [124]:
# creating 2x2 array with random value 

x = np.random.random((2,2))
print(x)

[[0.66996678 0.04780959]
 [0.77124362 0.38801325]]


In [116]:
# creating array within range(0-30) with step value(5)
x = np.arange(0,30,5)
print(x)

[ 0  5 10 15 20 25]


In [120]:
# craeting sequence of n values(10) in range (0-5)
x = np.linspace(0,100,10,dtype='int')
print(x)

[  0  11  22  33  44  55  66  77  88 100]


In [ ]:
# reshaping mxn array into n  mxn array eh: 2 3x2 arrays

a = np.array([[1,2,3,4],
              [5,6,7,8],
              [3,4,5,6]])

a.reshape(2,2,2) 